import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import propertiesRouter from "./properties";
import commentsRouter from "./comments";
import structuresRouter from "./structures";
import sectorsRouter from "./sectors";
import swalesRouter from "./swales";
import clientBriefsRouter from "./clientBriefs";
import pathwaysRouter from "./pathways";
import zonesRouter from "./zones";
import configRouter from "./config";
import analyzeSiteRouter from "./analyzeSite";
import waterBudgetRouter from "./waterBudget";
import sensoryVectorsRouter from "./sensoryVectors";
import storageRouter from "./storage";
import conceptRenderRouter from "./conceptRender";
import publicRouter from "./public";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(configRouter);
router.use(propertiesRouter);
router.use(commentsRouter);
router.use(structuresRouter);
router.use(sectorsRouter);
router.use(swalesRouter);
router.use(clientBriefsRouter);
router.use(pathwaysRouter);
router.use(zonesRouter);
router.use(sensoryVectorsRouter);
router.use(analyzeSiteRouter);
router.use(waterBudgetRouter);
router.use(storageRouter);
router.use(conceptRenderRouter);
router.use(publicRouter);

export default router;
