// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/terraguard-dashboard/CommandCenterHub.tsx": () => import("../components/mockups/terraguard-dashboard/CommandCenterHub.tsx"),
  "./components/mockups/terraguard-dashboard/LayerStack.tsx": () => import("../components/mockups/terraguard-dashboard/LayerStack.tsx"),
  "./components/mockups/landing/FieldAlmanac.tsx": () => import("../components/mockups/landing/FieldAlmanac.tsx"),
  "./components/mockups/landing/LivingMosaic.tsx": () => import("../components/mockups/landing/LivingMosaic.tsx"),
  "./components/mockups/terraguard-sidebar/Blueprint.tsx": () => import("../components/mockups/terraguard-sidebar/Blueprint.tsx"),
  "./components/mockups/terraguard-sidebar/Clean.tsx": () => import("../components/mockups/terraguard-sidebar/Clean.tsx"),
  "./components/mockups/terraguard-sidebar/Field.tsx": () => import("../components/mockups/terraguard-sidebar/Field.tsx"),
  "./components/mockups/terraguard-sidebar/Tactical.tsx": () => import("../components/mockups/terraguard-sidebar/Tactical.tsx")
};
